services:
  - type: web
    name: vastu-server
    env: node
    buildCommand: |
      # Install root dependencies
      npm install
      
      # Install server dependencies
      cd server
      npm install --production
      cd ..
      
      # Build client
      cd client
      npm install
      npm run build
      cd ..
      
      # Create a server directory in the root and copy server files
      mkdir -p /opt/render/project/server
      cp -r server/* /opt/render/project/server/
      
    startCommand: cd /opt/render/project/server && node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        fromDatabase:
          name: vastu-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
    plan: free
    region: oregon
    autoDeploy: true