services:
  - type: web
    name: vastu-server
    env: node
    buildCommand: pwsh -File ./render-build.ps1
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        fromDatabase:
          name: vastu-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
    plan: free
    region: oregon
    autoDeploy: true