services:
  - type: web
    name: vastu-server
    env: node
    buildCommand: npm install && cd client && npm install && npm run build
    startCommand: bash start.sh
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        fromDatabase:
          name: vastu-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
    plan: free
    region: oregon
    autoDeploy: true